### ISSUE TITLE
win apps

### ISSUE THREAD

**Issue by darkata** [peter9teufel/raspmedia#1]
hello your project look good, but the win app have some problems.

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Peter Neunteufel\Documents\GitRepos\raspmedia\Desktop\build\Ras
pMediaApp\out00-PYZ.pyz\packages.rmgui.AppFrame", line 43, in **init**
  File "C:\Users\Peter Neunteufel\Documents\GitRepos\raspmedia\Desktop\build\Ras
pMediaApp\out00-PYZ.pyz\packages.rmgui.RemoteNotebook", line 128, in SearchHosts

......

**Comment by peter9teufel** [comment]
Did you compile it yourself or did you use the .exe file from http://bit.do/raspmedia ? Can you provide the complete error log that i can track down where the problem cones from? Greets, Peter

**Comment by darkata** [comment]
sorry for the delay, i download from http://www.yellowframe.net/rmtools/rmtools.html 

in windows 

C:\Users\root>"C:\Users\root\Downloads\RM_Control_Windows (1)\RaspMedia Control.
exe"
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Peter Neunteufel\Documents\GitRepos\raspmedia\Desktop\build\RaspMediaApp\out00-PYZ.pyz\packages.rmgui.AppFrame", line 43, in **init**
  File "C:\Users\Peter Neunteufel\Documents\GitRepos\raspmedia\Desktop\build\RaspMediaApp\out00-PYZ.pyz\packages.rmgui.RemoteNotebook", line 128, in SearchHosts

  File "C:\Users\Peter Neunteufel\Documents\GitRepos\raspmedia\Desktop\build\RaspMediaApp\out00-PYZ.pyz\packages.rmnetwork.udpconnector", line 26, in sendMessag
e
  File "C:\Users\Peter Neunteufel\Documents\GitRepos\raspmedia\Desktop\build\RaspMediaApp\out00-PYZ.pyz\packages.rmnetwork.udpconnector", line 41, in _sendMessa
ge
  File "C:\Users\Peter Neunteufel\Documents\GitRepos\raspmedia\Desktop\build\RaspMediaApp\out00-PYZ.pyz\socket", line 224, in meth
socket.error: [Errno 10049] La direcci¾n solicitada no es vßlida en este contexto
-----------------------------------"The requested address is not valid in this context"                                               

in mac version
 the raspmedia control load the windows but never find the raspberry

thanks

**Comment by bertsmelik** [comment]
Hi Peter,

like your project and the idea to push images from a desktop. I would like to use this for a primary school (in Netherlands), where useres normaly do not have admin rights on their windows 7 desktop.
I found that in order to make the Raspmedia unit visible for the desktop user, we must disable the windows firewall completely. That cannot be done bij the user and to leave the firewall disabled all the time seems dagerous to me.
Can you give us some guidance on how to open the firewall more precisely to enable this solution to work for the non-admin user?
Best regards, Bert

**Comment by bertsmelik** [comment]
Hi Peter,

sorted it out!
Turns out that the Windows 7 PC did not ask permission to change the firewall. Now it does.

Thanks, Bert

**Comment by peter9teufel** [comment]
Hi bertsmelik,
You can create a rule in the settings of the windows firewall that allows the RaspMedia App you want to use to connect to the network. This way the firewall keeps turned on but raspmedia will work.

**Comment by peter9teufel** [comment]
Hi darkata,
seems like UDP broadcasts, which are used to search the whole network for players, are not possible in your network? Check if UDP is allowed and possible and come back. Maybe we will find a solution ;)

**Comment by bertsmelik** [comment]
Hi Peter!

We have installed RaspMedia in the school and they like it a lot! The issue we had is with the network in the school. It is run by a 3rd party which blocks all unknown network traffic. Therefore we have (temporarily) put the whole thing on a seperate network. However, we would like to put everything on the school's network and for that we need to know which conditions must be met to do so. We have seen that the Windows program uses port 60001 plus a number of other ports, which seem to increment for each action. That is confusing as we cannot figure out which port(range)s can be used.
Could you give me the info about which ports (UDP and/or TCP) are used. With that information we can ask the network provider with information that makes sense!
Thanks in advance!

Best regards, Bert

**Comment by peter9teufel** [comment]
Hi Bert,
RaspMedia uses UDP Port 60001 for UDP commands and TCP Port 60020 for TCP File transfers (e.g. sending images to the player or loading preview in RaspMedia Image Transfer).

BR,
Peter

**Comment by bertsmelik** [comment]
Thanks Peter,

We will try to get it to work with this information.

Best regards, Bert

**Comment by peter9teufel** [comment]
Hey @darkata ,
I found a minor issue according the windows applications and changed a flag in compiling the applications for windows, i uploaded new windows executables to http://bit.do/raspmedia
Hope it works now for you.
Additionally I tagged a new release today bringing additional features to the player, check it out in the repo releases section --> https://github.com/peter9teufel/raspmedia/releases/tag/v1.1

**Comment by bertsmelik** [comment]
Hi Peter!

The party controlling the school network, after draging their feet, have now indicated that they cannot remove the blockage of UDP trafffic on a per-school basis. In fact they are simply unwilling: the not-invented-here syndrome! 
So, the Windows program cannot find the RaspMedia server(s).
My question to you now is: would it be possible to introduce a runtime option in the windows program to specify the IP-address of the RaspMedia server? That way we would avoid the use of UDP and address the RaspMedia server directly.

Thanks, Bert

**Comment by peter9teufel** [comment]
Hi!
Already had another request for manually entering an IP, maybe we'll need it for ourselves too. I have to look when I will have time to include it, maybe I can get it up and running in the next 2 or 3 weeks if my other projects allow it.

Regards,
Peter

**Comment by bertsmelik** [comment]
That would be great Peter!

Timing suits us very well.

Greetz, Bert

**Comment by peter9teufel** [comment]
I made a simple implementation that allows you to manually the IP of a single player to connect to it if no players can be found over UDP. This should work in windows 7 and above, XP is not supported. After entering the IP address and clicking OK the application connects to the player on the given IP. Finding players should be solved by this.

The question that arrises is, if only UDP broadcasts are blocked in your network or if all UDP traffic for my port is blocked. Most of the simple communication between remote application and player is done over UDP.

I can upload a new Windows EXE of RaspMedia Control and RaspMedia Image Transfer in the course of the day for you. I will tell you when the new executables are online.

Regards,
Peter

**Comment by peter9teufel** [comment]
Hi Bert,
new Windows EXE binaries for RaspMedia Control and RaspMedia ImageTransfer are now online for download under http://bit.do/raspmedia
As mentioned before it should resolve the issue of not finding the player by entering a player IP, hopefully the UDP configuration of your school network only blocks UDP broadcasts, if it also blocks other UDP messages it might prohibit the other communication with the players too.

You may also consider a new feature that was introduced in the last RaspMedia Version that allows you to bring media files on the player using a USB Stick - just create a folder called "raspmedia" on the root of a FAT32 formatted USB Stick, put your media files for the player in there, connect it to the player and boot the player. The player will then delete the old media files, copy the new ones and change the configuration based on the new media files enabling/disabling image and video processing according to the presence of images and/or videos.
Adding any type of file in the raspmedia folder on the USB Stick that is called "update" (e.g. an "update.txt" or an "update.doc") should cause the player to not delete the files currently on the player but adding the new media files to the existing ones on the player. But be aware that any file on the player that has the same filename as one of the new mediafiles will be overwritten.

Hope that helps, let me know if bypassing the need of the UDP broadcast search solved the problem or if the other communication is blocked too.

Best regards,
Peter

**Comment by bertsmelik** [comment]
Thanks Peter!

Hope to test it before we get away for a 3-week period.
I will let you konw the results!

Bert

2015-02-09 9:40 GMT+01:00 Peter 9teufel notifications@github.com:

> Hi Bert,
> new Windows EXE binaries for RaspMedia Control and RaspMedia ImageTransfer
> are now online for download under http://bit.do/raspmedia
> As mentioned before it should resolve the issue of not finding the player
> by entering a player IP, hopefully the UDP configuration of your school
> network only blocks UDP broadcasts, if it also blocks other UDP messages it
> might prohibit the other communication with the players too.
> 
> You may also consider a new feature that was introduced in the last
> RaspMedia Version that allows you to bring media files on the player using
> a USB Stick - just create a folder called "raspmedia" on the root of a
> FAT32 formatted USB Stick, put your media files for the player in there,
> connect it to the player and boot the player. The player will then delete
> the old media files, copy the new ones and change the configuration based
> on the new media files enabling/disabling image and video processing
> according to the presence of images and/or videos.
> Adding any type of file in the raspmedia folder on the USB Stick that is
> called "update" (e.g. an "update.txt" or an "update.doc") should cause the
> player to not delete the files currently on the player but adding the new
> media files to the existing ones on the player. But be aware that any file
> on the player that has the same filename as one of the new mediafiles will
> be overwritten.
> 
> Hope that helps, let me know if bypassing the need of the UDP broadcast
> search solved the problem or if the other communication is blocked too.
> 
> Best regards,
> Peter
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/peter9teufel/raspmedia/issues/1#issuecomment-73473789
> .

## 

Groet, Bert Smelik

**Comment by bertsmelik** [comment]
Hi Peter,

Thanks for being so responsive!

Just downloaded and tested your new programs RaspMedia Control and
RaspMedia Image Transfer.

_RaspMedia Control_
Seems t work just fine. After not finding the server it asks for an
IP-address and then I have an interface to the RaspMedia server.
I could: Stop and start (Play) the server. Also Identify and Reboot worked
just fine.

_RaspMedia Image Transfer_
After not finding the server it asks for an IP-address and then start
looking at the image files of the player in a seperate window:
- windows title: "loading files"
- windows content: a progress bar that never ends and the text:
  "Receiving image files from your player"

so it seems that the protocol to transfer the information back and forth is
blocked.

As I wrote you before: I will be away for the coming 3-week period. So: no
need to rush!

Best regards, Bert

2015-02-09 13:26 GMT+01:00 Bert Smelik bert@smelikdamsteeg.net:

> Thanks Peter!
> 
> Hope to test it before we get away for a 3-week period.
> I will let you konw the results!
> 
> Bert
> 
> 2015-02-09 9:40 GMT+01:00 Peter 9teufel notifications@github.com:
> 
> > Hi Bert,
> > new Windows EXE binaries for RaspMedia Control and RaspMedia
> > ImageTransfer are now online for download under http://bit.do/raspmedia
> > As mentioned before it should resolve the issue of not finding the player
> > by entering a player IP, hopefully the UDP configuration of your school
> > network only blocks UDP broadcasts, if it also blocks other UDP messages it
> > might prohibit the other communication with the players too.
> > 
> > You may also consider a new feature that was introduced in the last
> > RaspMedia Version that allows you to bring media files on the player using
> > a USB Stick - just create a folder called "raspmedia" on the root of a
> > FAT32 formatted USB Stick, put your media files for the player in there,
> > connect it to the player and boot the player. The player will then delete
> > the old media files, copy the new ones and change the configuration based
> > on the new media files enabling/disabling image and video processing
> > according to the presence of images and/or videos.
> > Adding any type of file in the raspmedia folder on the USB Stick that is
> > called "update" (e.g. an "update.txt" or an "update.doc") should cause the
> > player to not delete the files currently on the player but adding the new
> > media files to the existing ones on the player. But be aware that any file
> > on the player that has the same filename as one of the new mediafiles will
> > be overwritten.
> > 
> > Hope that helps, let me know if bypassing the need of the UDP broadcast
> > search solved the problem or if the other communication is blocked too.
> > 
> > Best regards,
> > Peter
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/peter9teufel/raspmedia/issues/1#issuecomment-73473789
> > .
> 
> ## 
> 
> Groet, Bert Smelik

## 

Groet, Bert Smelik

**Comment by peter9teufel** [comment]
Similar to sending UDP commands from desktop to player and vice versa, files are transmitted over a TCP socket on port 60020.
If that is also blocked by your network company I'm afraid that there's not more I can do for you. I'm using this project combined with other applications thus I will stick to the network/port setup.

Best regards,
Peter

**Comment by peter9teufel** [comment]
One more idea...

The "Receiving image files from your player" indicates that the desktop application requests thumbnails of all images currently on the player to be able to show a preview.

What you can try as a last option is to make sure that your RaspMedia players are running with the latest source, older versions had no thumbnail creation and will also not react to the request to get the thumbnail data over TCP.
That can also be the reason why the application is stuck at this point.

BR,
Peter

**Comment by Cbuckwoj** [comment]
Hi Peter, 

Thank you for your work and this great application.  I have set up my pi2 and have downloaded the precompiled exes from your site.  

The player on the pi2 has been running great but has rebooted on its own several times in last 24 hours.  I am unsure of what to look at for a cause to this. 

On the Windows machines I can use the Control software and see the unit and see the files on it. 
I can identify the unit and also stop, start.  

What I have been unable to do is to send a file to the unit.  2 things have happened.  One it will show a proggress bar and then it will dissappear,  but refreshing the device will not show the file on the player.  

or two it will hang on sending file and a searching for player progress bar will also come up and hang there.  

I have tried this on a windows 8.1 and a windows 7 machine on the network.  

Any help would be appreciated.  

Chuck

**Comment by peter9teufel** [comment]
Hi Chuck,
for the reboots I'm not sure, I have a Pi2 for development which recently ran for hours without any trouble, make sure it has a sufficient power adapter, maybe that could be part of the problem?

If you have installed the very latest version yesterday the precompiled versions of the control software won't work properly. I'm going to upload new executables today so check back later for a fresh download.

BR,
Peter
