### ISSUE TITLE
Manual conf

### ISSUE THREAD

**Issue by psyzion** [peter9teufel/raspmedia#3]
hey.

I have a couple of lan in different place, connected to a server with VPN.

192.168.50.*
192.168.60.*
Etc
Server 192.168.5.100

send a UDP broadcast packet to different subnet is not working with my VPN router.

Is it easy to conf the mediacontrol "by hand", the players are going to have static ip.

So i can control my players on the different subnet, from the server PC?

Sorry for my bad english, writing on a small telephone :)

And thank u for a great applikation!!

/Nicklas

**Comment by peter9teufel** [comment]
hi @psyzion !
hmmmm..... have to think about that for a minute but I think that I can find an elegant solution for you ;-)
But it will take some time to include a manual connect functionality to a specific IP in the RaspMedia Control desktop application.

What you actually can do until the release I tagged today is control and config the player using simple UDP string commands, you can send these commands using any application that allows you to send a string over UDP to a specific IP Address on port 60001. I tested it with "PacketSender" and it works quite well, it's a free network tool that you can download at http://packetsender.com/
Just set it to UDP, port 60001, Resend to 0 (sends command only once), IP of your player and type the command in the ASCII representation field. PacketSender not only allows to send packets but you can also name them and save them to easily reuse them.

Best regards,
Peter

**Comment by Carnz06** [comment]
Thank you for your help.  How do I change the pic size out put. Depending
on the monitor.  Is it ssh?

**Comment by Carnz06** [comment]
Here's one for you. I would like it to pull pictures from my Windows
computer via networking is that possible?

**Comment by Carnz06** [comment]
Sorry for bothering you so much.  But the monitor I'm using is 1600x900. Is
there a easy way to switch output to this?

**Comment by peter9teufel** [comment]
There's in fact an easy way, mount the SD Card of the raspberry on your desktop computer, there should be a boot partition with a config.txt file on it. Open it and find the section with HDMI group and HDMI mode, set it to the following:

hdmi_group=2
hdmi_mode=83

unmount the SD, put it back in your Raspberry and boot it up, the HDMI output should work with 1600x900 now.

You can find a list of HDMI modes here --> http://www.raspberrypi.org/documentation/configuration/config-txt.md

In case you need to change the mode again ;)

**Comment by peter9teufel** [comment]
What do you mean by pulling pictures from your Windows machine? Somehow like mounting a Windows share as network drive on the raspberry? if so, you may set up your Raspberry to automatically mount the network share at startup and softlink the media folder of the RaspMedia player to that share.

I haven't tested such a setup so it may work but no guarantees here. Also you would need to check out how to access and mount such a share on the raspberry pi.

**Comment by peter9teufel** [comment]
@psyzion Current versions of the desktop applications allow to enter an IP if no player can be found, hope that helps.

Due to the fact that no replies came for more than 2 months this will be closed now.
