### ISSUE TITLE
24/7

### ISSUE THREAD

**Issue by redraw** [peter9teufel/raspmedia#4]
Do you have expirience running your software 24 hours a day?

**Comment by peter9teufel** [comment]
We used it over a period of I think 3 or 4 days, running videos in a loop for about 14 hours a day and had no problems. We also use it in a restaurant to show the available menus so it's running there about 14 hours a day, 7 days a week.
Never did a real 24/7 but I think it the software should work in long time use if the raspberry itself has a stable and good enough power resource etc.

**Comment by redraw** [comment]
thanks for sharing!
