### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by SFR75** [peter9teufel/raspmedia#5]
Hello Peter,

Sorry I post it here, but I can't figure out how I can contact you elsewhere.
Just a quick question - I'm looking for raspberry deployment, where I can just 
play video by pressing an external button (via GPIO). I wonder if I can use your
digital signage solution for that, or there is no such interactive feature possible ?

Sincerely
Mikhail

**Comment by peter9teufel** [comment]
Hi Mikhail,
never tried controlling stuff with buttons via GPIO, sounds like the whole digital signage solution is a bit of overkill for what you want. Maybe it would be better to google a bit how you can solve the stuff with the GPIO button, triggering a video is relatively simple by just using a script to call omxplayer.

Greets,
Peter
