### ISSUE TITLE
Not working with latest release of Jessie

### ISSUE THREAD

**Issue by MakerFront** [peter9teufel/raspmedia#6]
I tried to set this up on Jessie on a Rpi2 and it had some issues. Anyone feel like playing with it to get it going again? This is amazing if it works.

**Comment by MakerFront** [comment]
Forgot to mention, I followed the instructions to the letter.

**Comment by peter9teufel** [comment]
Hi!
What exactly crashes or does not work? I haven't used or tested this OpenSource version for about 9 months so as it was improved commercially for a customer, some details on what exactly happens could help ;-)

Greetz,
Peter

**Comment by MakerFront** [comment]
I know I'm asking for trouble without the issue exactly in front of me. I had to run to work this morning and I forgot to write it down.

If you have a spare pi2 around, may be easier to just toss it on there.

It looks like the installation doesn't complete because there is no raspmedia directory created in the pi directory. I copied it in with winscp, rebooted, and it tried to launch but had errors loading modules.

The first error was from line 8 in rasp-mediaplayer.py

As for the other errors, I would have to take a look when I get home later, sorry for not having everything in front of me.

I figured something changed in the Raspbian image, or maybe some other environment change happened that broke it. (not your code, I trust yours was working in the 6-20-14 release)

Thanks! And I really do appreciate the work and the fact that you responded!

-Mike

**Comment by peter9teufel** [comment]
Ok, I'll look into it as soon as I have time, hope to find time till sunday, I'm currently a bit busy, hope you have some few days to wait :-)

BR,
Peter

**Comment by MakerFront** [comment]
Of course! Any help would be appreciated! Thanks so much for looking into it!

-Mike

**Comment by peter9teufel** [comment]
I've setup a player with latest Jessie image now and fixed 2 codelines with minor issues. It should work now. Please try a fresh install on fresh Jessie image.

One more note: Jessie boots to desktop by default so make sure before you start the installation boot up first, go to system settings "Raspberry Configuration" and set "Boot to CLI",disable auto login and expand the filesystem. After those steps do the installation as described in the README.

Please report back if it is working.

Greets,
Peter

**Comment by MakerFront** [comment]
Tried with a fresh install of Jessie lite, still had the same errors (and I had to copy in the raspmedia directory in).

**Comment by peter9teufel** [comment]
What do you mean wirh "jessie lite"? This is intended for the full raspbian image
Am 20.03.2016 02:38 schrieb MakerFront notifications@github.com:Tried with a fresh install of Jessie lite, still had the same errors (and I had to copy in the raspmedia directory in).

**Comment by peter9teufel** [comment]
Use the standard Jessie image, the lite distribution is maybe missing required packages that the default jessie distribution has included

**Comment by MakerFront** [comment]
I'll try with the full version, sorry.

**Comment by YossarianBGD** [comment]
Your instructions worked perfectly @peter9teufel 

It would be nice to put that note about cli-only and no auto-login for Jessie  in README.
